Controle_Estoque/Controllers/EntradaSaidaController.cs
using DataAcess;
using DataAcess.Data.Repository.IRepository;
using DataAcess.Libraries.Filter;
using DataAcess.Model;
using DataAcess.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Controle_Estoque.Controllers
{
    public class EntradaSaidaController : Controller
    {
        private IProdutoRepository _repoProduto { get; set; }
        private IEntradaSaidaRepository _repoEntradaSaida { get; set; }
        private IEstoqueRepository _repoEstoque { get; set; }

        public EntradaSaidaController(IProdutoRepository repoProduto, IEntradaSaidaRepository repoEntradaSaida, IEstoqueRepository repoEstoque)
        {
            _repoProduto = repoProduto;
            _repoEntradaSaida = repoEntradaSaida;
            _repoEstoque = repoEstoque;
        }

        public IActionResult Index()
        {
            var obj = new VMModalCadHome
            {
                ListProduto = _repoProduto.GetDropDownList(),
                EntradaSaida = new EntradaSaida(),
                Produto = new Produto(),
            };

            return View(obj);
        }
        public IActionResult Cadastrar(EntradaSaida entradaSaida)
        {

            _repoEntradaSaida.Add(entradaSaida);
          
            var qtdEstoque = _repoEstoque.Get(a => a.ProdutoId == entradaSaida.ProdutoId);

            if(qtdEstoque == null)
            {
                var objEstoque = new Estoque
                {
                    ProdutoId = entradaSaida.ProdutoId,
                    QuantidadeEstoque = entradaSaida.Quantidade
                };

                _repoEstoque.Add(objEstoque);
            }else if (entradaSaida.Tipo == "ENTRADA")
            {
                var objEstoque = new Estoque
                {
                    ProdutoId = entradaSaida.ProdutoId,
                    QuantidadeEstoque = qtdEstoque.QuantidadeEstoque + entradaSaida.Quantidade
                };
            }
            else
            {
                var objEstoque = new Estoque
                {
                    Id =  qtdEstoque.Id,
                    ProdutoId = entradaSaida.ProdutoId,
                    QuantidadeEstoque = qtdEstoque.QuantidadeEstoque - entradaSaida.Quantidade
                };

                _repoEstoque.Update(objEstoque);
            }
            return RedirectToAction("Index", "Estoque");
        }
    }
}

Controle_Estoque/Controllers/EstoqueController.cs
using DataAcess;
using DataAcess.Data.Repository.IRepository;
using DataAcess.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Controle_Estoque.Controllers
{
    public class EstoqueController : Controller
    {
        public IEstoqueRepository _estoque { get; set; }
        public EstoqueController(IEstoqueRepository estoque)
        {
            _estoque = estoque;
          
        }

   

        public IActionResult Index()
        {
            ViewBag.lista= _estoque.GetAll();

            return View();
        }
    }
}

Controle_Estoque/Controllers/ProdutoController.cs
using DataAcess.ViewModel;
using DataAcess.Data.Repository.IRepository;
using DataAcess.Model;
using Microsoft.AspNetCore.Mvc;
using DataAcess.Data;
using DataAcess;

namespace Controle_Estoque.Controllers
{
    public class ProdutoController : Controller
    {
        private IProdutoRepository _produto { get; set; }

        public ICategoriaRepository _Categoria { get; set; }

        private IFornecedorRepository _fornecedor { get; set; }
        private ITipoUnitarioRepository _tipoUnitario { get; set; }

        public IEstoqueRepository _estoqueRepository { get; set; }

        public AppDataContext _db { get; set; }

        public ProdutoController(ICategoriaRepository categoria, AppDataContext db, IFornecedorRepository fornecedor, ITipoUnitarioRepository tipoUnitario, IProdutoRepository produto, IEstoqueRepository estoque)
        {
            _produto = produto;
            _Categoria = categoria;
            _fornecedor = fornecedor;
            _tipoUnitario = tipoUnitario;
            _estoqueRepository = estoque;
            _db = db;

        }
        public IActionResult Index()
        {
            var obj = new VMModalCadHome
            {
                ListCategorias = _Categoria.GetCategoriaList(),
                ListFornecedor = _fornecedor.GetDropDownList(),
                ListTipoUnitario = _tipoUnitario.GetDropDownList(),
                Categoria = new  Categoria(),
                Fornecedor = new Fornecedor(),
                Produto = new Produto(),
                TipoUnitario = new TipoUnitario()
            };

        
            return View(obj);
        }

        [HttpPost]
        public IActionResult CadastrarProduto(VMModalCadHome db)
        {

            if (ModelState.IsValid && db.Produto.EstoqueMaximo >= db.Produto.EstoqueMinimo)
            {
                _produto.Add(db.Produto);
                return RedirectToAction(nameof(Index));
            }
            else
            {

                return RedirectToAction(nameof(Index));
            }


        }

        public IActionResult CadastrarProduto()
        {


            return View();
        }
    }
}

Controle_Estoque/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Controle_Estoque</title>
    <!-- jQuery Modal -->

    <link rel="stylesheet" href="/lib/bootstrap-4.1.3-dist/css/bootstrap-grid.css">
    <link rel="stylesheet" href="/lib/bootstrap-4.1.3-dist/css/bootstrap-grid.min.css">
    <link rel="stylesheet" href="/lib/bootstrap-4.1.3-dist/css/bootstrap.css">
    <link rel="stylesheet" href="/lib/bootstrap-4.1.3-dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/estilos.css">


    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css" />
</head>
<body>

    <nav class="navbar  navbar-expand-lg navbar-light bg-light " style="padding: 0;margin: 1;">
        <!-- <a class="navbar-brand" href="#">Navbar</a> -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="HeaderNavDefault collapse navbar-collapse HeaderNavDefault" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item active">
                    <a style="color: white;" class="nav-link " href="#">HOME <span class="sr-only">(current)</span></a>
                </li>

                <li class="nav-item dropdown">
                    <a style="color: white;" class=" nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        CADASTRAR
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" asp-controller="Produto" asp-action="Index">Produto</a>
                        <a href="#CadastroBairro" rel="modal:open" class=" dropdown-item" href="#">Fornecedor</a>
                        <a href="#CadastroCategoria" rel="modal:open" class="dropdown-item" href="#">Categoria</a>
                        <a href="#CadastroTipoUnitario" rel="modal:open" class="dropdown-item" href="#">Tipo Unitário</a>
                    </div>
                </li>

                <li class="nav-item active">
                    <a style="color: white;" class=" nav-link" asp-controller="Estoque" asp-action="Index" >ESTOQUE ATUAL <span class="sr-only">(current)</span></a>
                </li>

                <li class="nav-item active">
                    <a style="color: white;" class="FontColorWhite nav-link" asp-controller="EntradaSaida" asp-action="Index">ENTRADA/SAIDA <span class="sr-only">(current)</span></a>
                </li>

                <li class="nav-item active">
                    <a style="color: white;" class="FontColorWhite nav-link" href="#">RELATÓRIO <span class="sr-only">(current)</span></a>
                </li>

            </ul>
            <form class="form-inline my-2 my-lg-0">
                <button class="btn  m-1 BtnColorGreen">Logout</button>
                <label style="color: white;">Olá Breno</label>
                <!--Adicionar Imagem- <img src="#"> -->
            </form>
        </div>
    </nav>


    <div class="container">
        <main role="main" class="pb-3">
            <partial name="/Views/Partial/_PartialModal.cshtml"></partial>

            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Controle_Estoque - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="js/jquery-3.5.1.min.js"></script>
    <script src="lib/bootstrap-4.1.3-dist/js/bootstrap.js"></script>
    <script src="lib/bootstrap-4.1.3-dist/js/bootstrap.min.js"></script>
    <script src="lib/bootstrap-4.1.3-dist/js/bootstrap.bundle.js"></script>
    <script src="lib/bootstrap-4.1.3-dist/js/bootstrap.min.js"></script>
    <script src="lib/bootstrap-4.1.3-dist/js/bootstrap.min.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>